app/models.py
luttes = {
''

}

app/views/forms.py
# ourapp/forms.py

from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email

class EmailPasswordForm(Form):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])

app/__init__.py
from flask import Flask
from flask import render_template
from .views.home import home
from .views.user import user

app = Flask(__name__, instance_relative_config=True)

app.config.from_object('config')
app.config.from_pyfile('config.py')
# Now we can access the configuration variables via app.config["VAR_NAME"].
from .util import assets

app.register_blueprint(home)
app.register_blueprint(user)

app/views/home.py
from flask import Blueprint, render_template

home = Blueprint('home', __name__)

@home.route('/')
def _home():
    # Do some stuff
    return render_template('lutte.html')

@home.route('/twitter/<msg>')
def _twitter(msg):
    from app.util.twitter import twitter
    api = twitter()
    print msg
    tweet = "Hello, world ! (%s)" % msg
    status = api.update_status(status=tweet)
    return "done"

app/views/user.py
# ourapp/views.py

from flask import Blueprint, render_template, redirect, url_for

from .forms import EmailPasswordForm

user = Blueprint('user', __name__)

@user.route('/login', methods=["GET", "POST"])
def login():
    form = EmailPasswordForm()
    if form.validate_on_submit():

        # Check the password and log the user in
        # [...]

        return redirect(url_for('index'))

    return render_template('login.html', form=form)

@user.route('/lutte', methods=["GET", "POST"])
def lutte():
    pass

app/templates/layout.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <title>{% block title %}Répertoire des luttes{% endblock %}</title>

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='img/favicon.png') }}" sizes="32x32">

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
  {% assets "home_css" %}
      <link rel="stylesheet" href="{{ ASSET_URL }}" />
  {% endassets %}

  <nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <img src="static/img/logo.png" style="height:60px;margin-right:20px;"><a id="logo-container" href="#" class="light-blue-text brand-logo">Répertoire des luttes</a>
      <ul class="right hide-on-med-and-down">
      </ul>

      <ul id="nav-mobile" class="side-nav">
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
</head>
<body>
  {% block body %}
  {% endblock %}
</body>
<footer class="page-footer">
  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
  <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
  {% assets "home_js" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endassets %}
  {% block javascript %}
  {% endblock %}

</footer>

</html>

app/templates/login.html
{% extends "layout.html" %}
{% block body %}
<div class="container">
  <div class="section">
    <div class="row">
      <form class="col s12" action="{{ url_for('user.login') }}" method="post">
        <h3 class="red-text">L' entreprise</h3>
        <div class="row">
          <div class="input-field col s12 m12 l6">
            <input id="nom_entreprise" type="text" class="validate">
            <label for="first_name">Nom de l'entreprise</label>
          </div>
          <div class="input-field col s12 m12 l3">
            <input id="code_postal" type="text" class="validate">
            <label for="last_name">Code postal</label>
          </div>
          <div class="input-field col s12 m12 l3">
            <input id="nb_employes" type="text" class="validate">
            <label for="last_name">Nombre d'employés</label>
          </div>
        </div>
        <div class="divider"></div>
        <h3 class="red-text">Le Contexte</h3>
        <div class="row">
          <div class="input-field col s12">
            <textarea id="contexte_accroche" class="materialize-textarea"></textarea>
            <label for="contexte_accroche">Accroche</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <textarea id="contexte_resume" class="materialize-textarea"></textarea>
            <label for="contexte_resume">Résumé</label>
          </div>
        </div>
        <div class="divider"></div>
        <h3 class="red-text">Le Combat</h3>
        <div class="row">
          <div class="input-field col s12">
            <textarea id="combat_accroche" class="materialize-textarea"></textarea>
            <label for="combat_accroche">Accroche</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <textarea id="combat_resume" class="materialize-textarea"></textarea>
            <label for="combat_resume">Résumé</label>
          </div>
        </div>
        {{ form.csrf_token }}
      </form>
    </div>
  </div>
</div>
{% endblock %}